# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57e291620c6f103ce482f2522154aa6b1f9559f65166afd5e81ae1ab9a4c1390644a03c5dcf6af66ff2fbc9178504c36692c9fe471c678c8b34c89641e3f197a

test:
  secret_key_base: 55d6aa946c9424413c8b0e1b5299c6b6aa30dac82924b7ef41e4ea8abdb7d421615adf2ecc05ee5250c3d70382bf9a5a5a525551a99b4b21514d037d9aaf7264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
